### ISSUE TITLE
Software quality 

### ISSUE THREAD

**Issue by AliHMohammad** [Team-AB-DevOps/ab-dev-ops#37]
Setup software quality tool.

Mere info:

https://github.com/who-knows-inc/KEA_DAT_DevOps_2024_Autumn/blob/main/00._Course_Material/01._Assignments/04._Sofware_Quality_Linting_CI/02._After/software_quality.md

## Requirement for Mandatory II

After you have setup a these code quality tools and gone through the issues, your group should create a brief document that answers the following questions:

  - Do you agree with the findings?

  - Which ones did you fix?

  - Which ones did you ignore?

  - Why?

While only one can setup the integration with SonarQube, everyone should be able to answer the questions above for the exam.

**Comment by Forkeh** [comment]
[Sonar Cloud](https://sonarcloud.io/summary/overall?id=Team-AB-DevOps_ab-dev-ops) 
[Code Climate](https://codeclimate.com/github/Team-AB-DevOps/ab-dev-ops)

Må lige tjekke om du har/kan få adgang til begge ting.

**Comment by Forkeh** [comment]
[Sonar Cloud](https://sonarcloud.io/summary/overall?id=Team-AB-DevOps_ab-dev-ops) 
[Code Climate](https://codeclimate.com/github/Team-AB-DevOps/ab-dev-ops)

Må lige tjekke om du har/kan få adgang til begge ting.
